#build project
FROM maven:3.8.5-openjdk-18-slim AS build
ARG src="ProPet Backend Server/src"
COPY $src /home/ProPet/backend/src
##parent pom
COPY pom.xml /home/ProPet
##child pom
ARG child_pom="ProPet Backend Server/pom.xml"
COPY $child_pom /home/ProPet/backend
RUN mvn -f /home/ProPet/backend/pom.xml clean package -Dmaven.test.skip

#package
FROM openjdk:18-alpine
COPY --from=build /home/ProPet/backend/target/backend-server-0.1.jar /ProPet/backend.jar
RUN mkdir -p "/ProPet/images/user"
RUN mkdir -p "/ProPet/images/pet"
EXPOSE 8080
ENTRYPOINT ["java","-jar","/ProPet/backend.jar"]